# Generated by Django 5.2.8 on 2026-05-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_origen', to='core.destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
