# Generated by Django 5.2.8 on 2026-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='viaje',
            name='core_viaje_origen__27569e_idx',
        ),
        migrations.AddField(
            model_name='usuario',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='comision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
