# Generated by Django 5.2.8 on 2026-03-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_viaje_core_viaje_origen__27569e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
