# Generated by Django 5.2.8 on 2026-03-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_viaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False, help_text='¿El mototaxista ya pagó la comisión a Kooneex?')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mototaxista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_comisiones', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_detalle', to='core.viaje')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
