# Generated by Django 5.2.8 on 2026-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='limite_deuda',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
